export const GAME_CATEGORIES = [
  { title: "Action", to: '/games/category/GAME_ACTION' },
  { title: "Adventure", to: '/games/category/GAME_ADVENTURE' },
  { title: "Arcade", to: '/games/category/GAME_ARCADE' },
  { title: "Board", to: '/games/category/GAME_BOARD' },
  { title: "Card", to: '/games/category/GAME_CARD' },
  { title: "Casino", to: '/games/category/GAME_CASINO' },
  { title: "Casual", to: '/games/category/GAME_CASUAL' },
  { title: "Education", to: '/games/category/GAME_EDUCATIONAL' },
  { title: "Music", to: '/games/category/GAME_MUSIC' },
  { title: "Puzzle", to: '/games/category/GAME_PUZZLE' },
  { title: "Racing", to: '/games/category/GAME_RACING' },
  { title: "Role Playing", to: '/games/category/GAME_ROLE_PLAYING' },
  { title: "Simulation", to: '/games/category/GAME_SIMULATION' },
  { title: "Sports", to: '/games/category/GAME_SPORTS' },
  { title: "Strategy", to: '/games/category/GAME_STRATEGY' },
  { title: "Trivia", to: '/games/category/GAME_TRIVIA' },
  { title: "Word", to: '/games/category/GAME_WORD' },
];
export const APP_CATEGORIES = [
  { title: 'Android Wear', to: '/apps/category/ANDROID_WEAR' },
  { title: 'Art and Design', to: '/apps/category/ART_AND_DESIGN' },
  { title: 'Auto and Vehicles', to: '/apps/category/AUTO_AND_VEHICLES' },
  { title: 'Beauty', to: '/apps/category/BEAUTY' },
  { title: 'Books and Reference', to: '/apps/category/BOOKS_AND_REFERENCE' },
  { title: 'Business', to: '/apps/category/BUSINESS' },
  { title: 'Comics', to: '/apps/category/COMICS' },
  { title: 'Communication', to: '/apps/category/COMMUNICATION' },
  { title: 'Dating', to: '/apps/category/DATING' },
  { title: 'Education', to: '/apps/category/EDUCATION' },
  { title: 'Entertainment', to: '/apps/category/ENTERTAINMENT' },
  { title: 'Events', to: '/apps/category/EVENTS' },
  { title: 'Finance', to: '/apps/category/FINANCE' },
  { title: 'Food and Drink', to: '/apps/category/FOOD_AND_DRINK' },
  { title: 'Health and Fitness', to: '/apps/category/HEALTH_AND_FITNESS' },
  { title: 'House and Home', to: '/apps/category/HOUSE_AND_HOME' },
  { title: 'Libraries and Demo', to: '/apps/category/LIBRARIES_AND_DEMO' },
  { title: 'Lifestyle', to: '/apps/category/LIFESTYLE' },
  { title: 'Maps and navigation', to: '/apps/category/MAPS_AND_NAVIGATION' },
  { title: 'Medical', to: '/apps/category/MEDICAL' },
  { title: 'Music and audio', to: '/apps/category/MUSIC_AND_AUDIO' },
  { title: 'News and magazines', to: '/apps/category/NEWS_AND_MAGAZINES' },
  { title: 'Parenting', to: '/apps/category/PARENTING' },
  { title: 'Personalization', to: '/apps/category/PERSONALIZATION' },
  { title: 'Photography', to: '/apps/category/PHOTOGRAPHY' },
  { title: 'Productivity', to: '/apps/category/PRODUCTIVITY' },
  { title: 'Shopping', to: '/apps/category/SHOPPING' },
  { title: 'Social', to: '/apps/category/SOCIAL' },
  { title: 'Sports', to: '/apps/category/SPORTS' },
  { title: 'Tools', to: '/apps/category/TOOLS' },
  { title: 'Travel and local', to: '/apps/category/TRAVEL_AND_LOCAL' },
  { title: 'Video players', to: '/apps/category/VIDEO_PLAYERS' },
  { title: 'Weather', to: '/apps/category/WEATHER' },
];
